# Flex your GitHub skills... by updating our website!

As a member of our lab, we would like you to update our "People" page to include you! Here we will lay out the steps for you to fork our lab website repository, add yourself to our "People" page, and lastly, send a pull request to the ROSSyndicate to make these changes on the official website. This is a great chance for you to employ those best practices that we reviewed in the ROSSyndicate Best Practices Guide [[will need to link later]].

## Directions:

 • Fork the [lab's website repository](https://github.com/ROSSyndicate/lab_website). 
<br>
 • Once in your own R environment, create a copy of Matt's bio folder (found in **content/authors/**), rename to your first name. 
<br>
 • Update `_index.md` to reflect your own bio.
<br>
 • Replace `avatar.jpg` with your own photo; name it `avatar.jpg`.
<br>
 • Commit the addition of you bio, then push the branch to your forked repository. 
<br>
 • In GitHub, submit a pull request with your suggested changes (i.e., including you!) to the website, following the best practices guide. Assign the review to Katie Willi, the lab and data manager.
